-- Church Management System - Database Schema
-- Este archivo contiene el esquema completo de la base de datos

-- 🔹 1. LIMPIEZA INICIAL (Solo para desarrollo)
-- DROP TABLE IF EXISTS public.income;
-- DROP TABLE IF EXISTS public.expenses;
-- DROP TABLE IF EXISTS public.members;
-- DROP TABLE IF EXISTS public.sectors;
-- DROP TABLE IF EXISTS public.profiles;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm"; 

-- Roles
CREATE TYPE app_role AS ENUM ('pastor', 'secretario');
CREATE TYPE church_role AS ENUM ('Miembro', 'Ministro', 'Diácono', 'Ayudante', 'Otro');

-- Perfil de usuario
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name text,
  role app_role DEFAULT 'secretario',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Sectores
CREATE TABLE public.sectors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);

INSERT INTO public.sectors (name) VALUES 
('Sector 1'), ('Sector 2'), ('Sector 3'),
('Sector 4'), ('Sector 5'), ('Sector 6');

-- Miembros
CREATE TABLE public.members (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  full_name text NOT NULL,
  dui text DEFAULT NULL,
  phone text DEFAULT NULL,
  address text DEFAULT NULL,
  baptism_date date DEFAULT NULL,
  is_baptized boolean GENERATED ALWAYS AS (baptism_date IS NOT NULL) STORED,
  sector_id bigint REFERENCES public.sectors(id) ON DELETE SET NULL,
  church_position church_role DEFAULT 'Miembro',
  status text DEFAULT 'Activo' CHECK (status IN ('Activo', 'Inactivo', 'Disciplinado')),
  created_by uuid REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- Índices optimizados
CREATE INDEX idx_members_sector ON public.members(sector_id);
CREATE INDEX idx_members_name ON public.members USING GIN (full_name gin_trgm_ops); 

-- Ingresos
CREATE TABLE public.income (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL, 
  amount decimal(10,2) NOT NULL CHECK (amount > 0),
  date date DEFAULT current_date NOT NULL,
  category text NOT NULL CHECK (category IN ('Diezmo', 'Ofrenda General', 'Pro-templo', 'Ofrenda Especial')),
  period text DEFAULT NULL, 
  member_id uuid REFERENCES public.members(id) ON DELETE SET NULL,
  sector_id bigint REFERENCES public.sectors(id) ON DELETE SET NULL,
  notes text DEFAULT NULL,
  created_by uuid REFERENCES auth.users(id) DEFAULT auth.uid(),
  deleted_at timestamptz DEFAULT NULL
);

CREATE INDEX idx_income_sector ON public.income(sector_id);
CREATE INDEX idx_income_date ON public.income(date); 

-- Gastos
CREATE TABLE public.expenses (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL, 
  amount decimal(10,2) NOT NULL CHECK (amount > 0),
  date date DEFAULT current_date NOT NULL,
  category text NOT NULL CHECK (category IN ('Servicios Basicos', 'Mantenimiento', 'Ayuda Social', 'Limpieza', 'Otros')),
  description text NOT NULL,
  receipt_url text DEFAULT NULL,
  created_by uuid REFERENCES auth.users(id) DEFAULT auth.uid(),
  deleted_at timestamptz DEFAULT NULL
);

-- Triggers

-- Nuevo usuario -> crear perfil automáticamente
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', 'secretario');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Actualización de timestamps
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = now(); 
   RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_members_modtime 
BEFORE UPDATE ON public.members 
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TRIGGER update_income_modtime 
BEFORE UPDATE ON public.income 
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TRIGGER update_expenses_modtime 
BEFORE UPDATE ON public.expenses 
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- RLS (Row Level Security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.income ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acceso total Staff" ON public.members FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Acceso total Staff" ON public.sectors FOR SELECT USING (true);
CREATE POLICY "Acceso total Staff" ON public.income FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Acceso total Staff" ON public.expenses FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Leer perfiles" ON public.profiles FOR SELECT USING (auth.role() = 'authenticated');
